"""vacaciones registros y ausenciass

Revision ID: 1f6baa977f8f
Revises: d8e9611d47ec
Create Date: 2025-05-06 15:57:08.438413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f6baa977f8f'
down_revision = 'd8e9611d47ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registros_horarios', sa.Boolean(), nullable=True))
        batch_op.drop_column('registros')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registros', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('registros_horarios')

    # ### end Alembic commands ###
