"""festivos2026

Revision ID: 2e220d6f9b94
Revises: cf06abb7098a
Create Date: 2025-12-18 10:02:07.564759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e220d6f9b94'
down_revision = 'cf06abb7098a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('festivo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('año', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('festivo', schema=None) as batch_op:
        batch_op.drop_column('año')

    # ### end Alembic commands ###
