"""relacion user empresa

Revision ID: 387141879be5
Revises: 62de940f0925
Create Date: 2025-04-30 07:40:58.047061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '387141879be5'
down_revision = '62de940f0925'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_user_empresa_id', 'empresa', ['empresa_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('empresa_id')

    # ### end Alembic commands ###
