"""pausas

Revision ID: 62de940f0925
Revises: 
Create Date: 2025-04-23 14:47:28.449614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62de940f0925'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ver_pausas', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.drop_column('ver_pausas')

    # ### end Alembic commands ###
