"""contratos

Revision ID: 65e58bbafd70
Revises: 80d2a3b9b66d
Create Date: 2025-05-12 08:02:17.763872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65e58bbafd70'
down_revision = '80d2a3b9b66d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contrato', schema=None) as batch_op:
        batch_op.alter_column('archivo',
               existing_type=sa.BLOB(),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contrato', schema=None) as batch_op:
        batch_op.alter_column('archivo',
               existing_type=sa.String(length=255),
               type_=sa.BLOB(),
               existing_nullable=False)

    # ### end Alembic commands ###
