"""cambiar horarios

Revision ID: 672e18ccca70
Revises: 22c7dfe6a2d4
Create Date: 2025-05-29 12:47:32.430269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '672e18ccca70'
down_revision = '22c7dfe6a2d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitud_cambio_horario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registro_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=True),
    sa.Column('nueva_fecha_hora', sa.DateTime(), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('estado', sa.String(length=10), nullable=True),
    sa.Column('token', sa.String(length=100), nullable=False),
    sa.Column('fecha_solicitud', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['registro_id'], ['registro.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solicitud_cambio_horario')
    # ### end Alembic commands ###
