"""Asociar festivos a empresas

Revision ID: 678222fe12c1
Revises: 1f6baa977f8f
Create Date: 2025-05-08 09:10:52.298885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '678222fe12c1'
down_revision = '1f6baa977f8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('festivo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_festivo_empresa', 'empresa', ['empresa_id'], ['id'])  # Aquí se agrega el nombre de la restricción

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('festivo', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('empresa_id')

    # ### end Alembic commands ###
