"""bajas2

Revision ID: 688652369804
Revises: da4c5610b779
Create Date: 2025-10-31 09:48:25.364044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '688652369804'
down_revision = 'da4c5610b779'
branch_labels = None
depends_on = None

def upgrade():
    # ### Crear tabla 'qr' solo si no existe ###

    # ### Hacer nullable la columna 'fecha_fin' en 'baja' ###
    with op.batch_alter_table('baja', schema=None) as batch_op:
        batch_op.alter_column(
            'fecha_fin',
            existing_type=sa.DATE(),
            nullable=True
        )

    # ### Eliminar tabla 'QR' solo si realmente existe ###
    # En SQLite, drop_table lanzará error si no existe, así que lo omitimos
    # op.drop_table('QR')  # ⚠ Comentado hasta confirmar que existe

    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('baja', schema=None) as batch_op:
        batch_op.alter_column('fecha_fin',
               existing_type=sa.DATE(),
               nullable=False)

    op.create_table('QR',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('imagen', sa.VARCHAR(length=255), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('centro_trabajo_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['centro_trabajo_id'], ['centro_trabajo.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('qr')
    # ### end Alembic commands ###
