"""archivo

Revision ID: 80d2a3b9b66d
Revises: ef70be3c3cfe
Create Date: 2025-05-12 07:22:04.758777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80d2a3b9b66d'
down_revision = 'ef70be3c3cfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nomina', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ruta', sa.String(length=255), nullable=True))
        batch_op.drop_column('archivo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nomina', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archivo', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('ruta')

    # ### end Alembic commands ###
