"""qrs

Revision ID: 933aa63f56de
Revises: 65e58bbafd70
Create Date: 2025-05-15 10:30:22.475602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '933aa63f56de'
down_revision = '65e58bbafd70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('QR',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imagen', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('centro_trabajo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['centro_trabajo_id'], ['centro_trabajo.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('QR')
    # ### end Alembic commands ###
