"""Add logo fields to Empresa

Revision ID: 94b4afeac3b7
Revises: 678222fe12c1
Create Date: 2025-05-08 11:54:36.890037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94b4afeac3b7'
down_revision = '678222fe12c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo_favicon', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('logo_login', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('logo_menu', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.drop_column('logo_menu')
        batch_op.drop_column('logo_login')
        batch_op.drop_column('logo_favicon')

    # ### end Alembic commands ###
