"""registro mod

Revision ID: cf06abb7098a
Revises: 688652369804
Create Date: 2025-11-19 13:18:39.450232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf06abb7098a'
down_revision = '688652369804'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aprobado_modificacion', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registro', schema=None) as batch_op:
        batch_op.drop_column('aprobado_modificacion')

    # ### end Alembic commands ###
