"""vacaciones registros y ausencias

Revision ID: d8e9611d47ec
Revises: 387141879be5
Create Date: 2025-05-06 15:49:09.972224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8e9611d47ec'
down_revision = '387141879be5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vacaciones', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('registros', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('ausencias', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('ausencias')
        batch_op.drop_column('registros')
        batch_op.drop_column('vacaciones')

    # ### end Alembic commands ###
