"""bajas

Revision ID: da4c5610b779
Revises: 730361bd2ebb
Create Date: 2025-10-31 09:35:28.858061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da4c5610b779'
down_revision = '730361bd2ebb'
branch_labels = None
depends_on = None


def upgrade():
    # Crear tabla baja
    op.create_table('baja',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('fecha_inicio', sa.Date(), nullable=False),
        sa.Column('fecha_fin', sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    # Comentamos o eliminamos la creación de qr
    # op.create_table('qr',
    #     sa.Column('id', sa.Integer(), nullable=False),
    #     sa.Column('imagen', sa.String(length=255), nullable=False),
    #     sa.Column('user_id', sa.Integer(), nullable=False),
    #     sa.Column('centro_trabajo_id', sa.Integer(), nullable=False),
    #     sa.ForeignKeyConstraint(['centro_trabajo_id'], ['centro_trabajo.id'], ),
    #     sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    #     sa.PrimaryKeyConstraint('id')
    # )

    # Si quieres, puedes dejar el drop de la antigua tabla QR
    op.drop_table('QR')

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('QR',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('imagen', sa.VARCHAR(length=255), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('centro_trabajo_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['centro_trabajo_id'], ['centro_trabajo.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('qr')
    op.drop_table('baja')
    # ### end Alembic commands ###
