"""nominas

Revision ID: ef70be3c3cfe
Revises: 94b4afeac3b7
Create Date: 2025-05-09 12:51:18.970438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef70be3c3cfe'
down_revision = '94b4afeac3b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nomina', schema=None) as batch_op:
        batch_op.alter_column('archivo',
               existing_type=sa.BLOB(),
               type_=sa.String(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nomina', schema=None) as batch_op:
        batch_op.alter_column('archivo',
               existing_type=sa.String(length=255),
               type_=sa.BLOB(),
               nullable=False)

    # ### end Alembic commands ###
